version: "3.3"
services: 
  javademo_service:
    build: .
    ports:
      - "8080:8080"
    container_name: student_management
    networks:
      - net2
    environment:
     - spring.datasource.url=jdbc:mysql://mySql_service:3306/sms
     - spring.datasource.username=root
     - spring.datasource.password=Global@145#
     - spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
     - spring.jpa.hibernate.ddl-auto=update
     - logging.level.org.hibernate.SQL=DEBUG
    depends_on:
      - mySql_service

  mySql_service:
    image: mysql:latest
    ports:
      - "3306:3306"
    container_name: mysql-container
    networks:
      - net2
    environment:
      MYSQL_ROOT_PASSWORD: Global@145#
      MYSQL_DATABASE: sms
      MYSQL_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
networks:
  net2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 12.12.0.0/24    
