version: '3.3'
services:
  mysqlservice:
    image: mysql:latest
    container_name: mysql-container
    ports:
     - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: Global@145#
      MYSQL_DATABASE: sms
      MYSQL_USERNAME: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  javaservice:
    container_name: java
    build: .
    ports:
      - 8080:8080
    environment:
      - spring.datasource.url=jdbc:mysql://mysqlservice:3306/sms
      - spring.datasource.username=root
      - spring.datasource.password=Global@145#
      - spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
      - spring.jpa.hibernate.ddl-auto=update
      - logging.level.org.hibernate.SQL=DEBUG
    depends_on:
      - mysqlservice
    restart: always
