version: "3.3"
services: 
  javademo_service:
    build: .
    ports:
      - "8080:8080"
    container_name: student_management
    networks:
      - net1
    environment:
     - spring.datasource.url=jdbc:mysql://database-1.cbnaefytg0xw.us-east-2.rds.amazonaws.com:3306/sms
     - spring.datasource.username=admin
     - spring.datasource.password=fstGfDkkYchQ4bvMSOMF
     - spring.jpa.properties.hibernate.dialect = org.hibernate.dialect.MySQL5InnoDBDialect
     - spring.jpa.hibernate.ddl-auto=update
     - logging.level.org.hibernate.SQL=DEBUG
networks:
  net2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 12.12.0.0/24    
